src/BikeSharing.Private.Web.Site/Models/Issue.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BikeSharing.Private.Web.Site.Models
{
    public class Issue
    {
        public int IssueId { get; set; }
        public string IssueType { get; set; }
        public string IssueTitle { get; set; }
        public string IssueDescription { get; set; }
        public bool IssueSolved { get; set; }
        public DateTime IssueDate { get; set; }
        public int UserId { get; set; }
        public int BikeId { get; set; }
        public string BikeSerialNumber { get; set; }
        public string RideType { get; set; }
        public int RideDuration { get; set; }
        public DateTime RideStart { get; set; }
        public DateTime RideStop { get; set; }
        public string RideFrom { get; set; }
        public string RideTo { get; set; }



    }

}

src/BikeSharing.Private.Web.Site/Models/IssueViewModels/IndexViewModel.cs
using BikeSharing.Private.Web.Site.Services.Pagination;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BikeSharing.Private.Web.Site.Models.IssueViewModels
{
    public class IndexViewModel
    {
        public PaginationInfo PaginationInfo { get; set; }
        public List<Issue> Issues { get; set; }
    }
}

src/BikeSharing.Private.Web.Site/Models/Ride.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BikeSharing.Private.Web.Site.Models
{
    public class Ride
    {
        public int Id { get; set; }
        [Display(Name = "Type")]
        public string RideType { get; set; }
        public int? Duration { get; set; }
        public DateTime? Start { get; set; }
        public DateTime? Stop { get; set; }
        [Display(Name = "From")]
        public string From { get;set;}
        [Display(Name = "To")]
        public string To { get; set; }
    }
}

src/BikeSharing.Private.Web.Site/Controllers/IssueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BikeSharing.Private.Web.Site.Services;
using BikeSharing.Private.Web.Site.Models.IssueViewModels;
using BikeSharing.Private.Web.Site.Services.Pagination;
using Microsoft.Extensions.Options;
using BikeSharing.Private.Web.Site.Configuration;
using Microsoft.AspNetCore.Authorization;

namespace BikeSharing.Private.Web.Site.Controllers
{
    public class IssueController : Controller
    {


        [HttpGet]
        public IActionResult Index(int page)
        {
            var vm = new IndexViewModel()
            {
                PaginationInfo = new PaginationInfo()
                {
                    ActualPage = page,
                    ItemsPerPage = 20
                }
            };

            return View(vm);
        }
    }
}

src/BikeSharing.Private.Web.Site/Controllers/PingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;

namespace BikeSharing.Private.Web.Site.Controllers
{
    [Route("api/[controller]")]
    public class PingController : Controller
    {
        private AppSettings _settings;
        public PingController(IOptions<AppSettings> options)
        {
            _settings = options.Value;
        }

        [HttpGet]
        public dynamic GetProfilesMicroserviceUrl()
        {
            return new
            {
                Data = "Ok " + DateTime.Now
            };
        }
        
    }
}

src/BikeSharing.Private.Web.Site/Views/Issue/Components/IssueList/Default.cshtml
@model BikeSharing.Private.Web.Site.Models.IssueViewModels.IndexViewModel

@{
    ViewData["Title"] = "View";
}

<div class="container page-container bsh-stations">
    <div class="row flex-items-xs-bottom">
        <div class="col-md-3 col-sm-12">
            <h1>Issues</h1>
        </div>
        <div class="col-md-9 col-sm-12 u-bottom u-align-right">
            @*<span>Showing @Html.DisplayFor(modelItem => modelItem.PaginationInfo.ItemsPerPage) of @Html.DisplayFor(modelItem => modelItem.PaginationInfo.TotalItems) stations - Page @(Model.PaginationInfo.ActualPage + 1) of @Html.DisplayFor(x => x.PaginationInfo.TotalPages)</span>*@
        </div>
    </div>

    <div class="margin-middle-top">
        <table class="table">
            <thead class="thead-default">
                <tr>
                    <th>
                        Type
                    </th>
                    <th>
                        Title
                    </th>
                    <th>
                        Solved
                    </th>
                    <th>
                        Bike serial
                    </th>
                    <th>
                        Ride
                    </th>
                    <th>
                        Start
                    </th>
                    <th>
                        Stop
                    </th>
                    <th>
                        From
                    </th>
                    <th>
                        To
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Issues)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.IssueType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IssueTitle)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IssueSolved)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BikeSerialNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.RideType)
                        </td>
                        <td>
                            <span>@item.RideStart.ToString("MM/dd HH:mm")</span>
                        </td>
                        <td>
                            <span>@item.RideStop.ToString("MM/dd HH:mm")</span>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.RideFrom)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.RideTo)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @*<div class="container">
            <div class="row">
                <div class="col-xs-4">
                    <nav>
                        <ul class="pagination pagination-sm u-float-left">
                            <li class="page-item">
                                <a class="page-link prev @Model.PaginationInfo.Previous" id="Previous"
                                   href="@Url.Action("Index","Issue", new { page = Model.PaginationInfo.ActualPage + -1 })
                                   aria-label="Previous">
                                    <span class="icon-ico-arrowcopy"></span>
                                    <span>Previous</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="col-xs-4 u-align-center">Page @(Model.PaginationInfo.ActualPage + 1) of @Html.DisplayFor(x => x.PaginationInfo.TotalPages)</div>
                <div class="col-xs-4">
                    <nav>
                        <ul class="pagination pagination-sm u-float-right">
                            <li class="page-item">
                                <a class="page-link next @Model.PaginationInfo.Next" id="Next"
                                   href="@Url.Action("Index","Issue", new { page = Model.PaginationInfo.ActualPage + 1 })"
                                   aria-label="Next">
                                    <span>Next</span>
                                    <span class="icon-ico-arrow-blue"></span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>*@
    </div>
</div>

src/BikeSharing.Private.Web.Site/Views/Issue/Index.cshtml
@model BikeSharing.Private.Web.Site.Models.IssueViewModels.IndexViewModel

@{
    ViewData["Title"] = "Rides";
}

@await Component.InvokeAsync("IssueList", new { vm = Model })

src/BikeSharing.Private.Web.Site/Views/Shared/_Layout.cshtml
@inject Microsoft.Extensions.Options.IOptions<BikeSharing.Private.Web.Site.Configuration.ApiSettings> ApiSettings

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BikeSharing.Private.Web.Site</title>
    <link rel="shortcut icon" type="image/png" href="~/images/favicon.ico" />
    <link rel="stylesheet" href="~/css/styles.css" />
</head>
<body>


    <header class="navbar">
        <nav>
            <div class="navbar-brand"></div>
            <div id="bd-main-nav">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Issue" asp-action="Index">Issues</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer class="bsh-footer">
        <div class="row">
            <div class="col-md-2 col-sm-12">
                <div class="bsh-footer-logo"></div>
            </div>
            <div class="col-md-6 col-sm-12">
                <ul class="bsh-footer-nav">
                    <li class="bsh-footer-nav-item"><a asp-area="" asp-controller="Issue" asp-action="Index">Issues</a></li>
                </ul>
            </div>
            <div class="col-md-4 col-sm-12">
                <ul class="bsh-footer-links">
                    <li class="bsh-footer-list-item"><a class="bsh-footer-link" href="#">Terms</a></li>
                    <li class="bsh-footer-list-item"><a class="bsh-footer-link" href="#">Privacy</a></li>
                    <li class="bsh-footer-list-item"><a class="bsh-footer-link" href="#">Contact</a></li>
                </ul>
            </div>
        </div>

        <div class="row margin-large-top">
            <div class="col-sm-2">
                <div class="bsh-footer-ms-logo"></div>
            </div>
            <div class="col-sm-8">
                <p class="bsh-footer-footnote">
                    This is a sample demo application for developers built with educational purposes only
                    Using following base urls for external services:
                </p>
                <ul class="bsh-footer-footnote">
                    <li><strong>Feedback:</strong> @ApiSettings.Value.IssuesApiUrl </li>
                    <li><strong>Rides:</strong> @ApiSettings.Value.RidesApiUrl </li>
                </ul>
            </div>
        </div>
    </footer>

    <script src="~/js/libs.js" asp-append-version="true"></script>
    <script src="~/js/main.js" asp-append-version="true"></script>

    @RenderSection("scripts", required: false)
</body>
</html>
<script type="text/javascript">
    $(document).ready(function () {
        var url = window.location.pathname;
        var substr = url.split('/');
        var urlaspx = substr[substr.length - 1];
        $('.nav').find('.is-active').removeClass('is-active');
        $('.nav li a').each(function () {
            if ((urlaspx.length === 0 || urlaspx.toLowerCase().indexOf('ride') > -1) && $(this).text().toLowerCase() === 'rides') {
                $(this).parent().addClass('is-active');
                return;
            }

            if (this.href.indexOf(urlaspx) >= 0 && urlaspx.toLowerCase() !== 'login' && urlaspx.length > 0) {
                $(this).parent().addClass('is-active');
            }
        });
    });
</script>